# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1260606a85473a1d3e5d41f6b66f81f7641124443efe3d6be7790bfaf145765a30106cb48881bfddc390026e202b5e94bc7fc5e4e1ad35f5ef0ce10af034be7e

test:
  secret_key_base: d35ef0226891fb04ea9ce050fa1347342fd35515b5a178ac955541973cf0387f33da7477abe83d2e8e073c45bf8414ad4871b4f936271eea647ab0bf27f7a28d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
